name: Build and Test codebase

on:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths-ignore:
      - '.gitignore'
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'README.md'
      - 'renovate.json'
      - 'docs/**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
        jvm_version: [21]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Setup JDK ${{ matrix.jvm_version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.jvm_version }}
      - name: Test
        run: ./gradlew test
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Assemble classes and test classes
        run: ./gradlew classes testClasses
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: ./gradlew build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  success:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 Build, Test and Check steps succeeded!"
